# Generated by Django 4.2 on 2023-05-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='featuredImage',
            new_name='featured_image',
        ),
    ]
