# Generated by Django 4.2 on 2023-05-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_featuredimage_blogs_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images'),
        ),
    ]
