# Generated by Django 4.2 on 2023-05-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_blogs_featured_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
